# Uncomment the next line to define a global platform for your project
platform :ios, '8.0'

target 'LYSCommonHUDDemo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for LYSCommonHUDDemo

  target 'LYSCommonHUDDemoTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'LYSCommonHUDDemoUITests' do
    inherit! :search_paths
    # Pods for testing
  end
pod 'MBProgressHUD', '~> 1.1.0'
end
